Utilisateur:
    type: entity
    table: utilisateur
    id:
        idClient:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_client
            generator:
                strategy: IDENTITY
    fields:
        login:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
        nom:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
        prenom:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
        civilite:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
        adresse:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
        pays:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
        telephone:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
        mail:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
    lifecycleCallbacks: {  }
